'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const OWNED_NAME = 'interlock-codex-policy.rules';
const MARKER = 'INTERLOCK-CODEX-POLICY 1';
const MODES = Object.freeze(['receive', 'participate']);
const AI_NAME = /^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/;

function failure(code, detail) {
  const error = new Error(detail ? 'codex_policy: ' + code + ': ' + detail : 'codex_policy: ' + code);
  error.code = code;
  return error;
}

function validConnectionName(value) {
  return typeof value === 'string' && value.length >= 2 && value.length <= 24 &&
    AI_NAME.test(value) && value.toLowerCase() !== 'all';
}

function isAbs(value) {
  return path.win32.isAbsolute(value) || path.posix.isAbsolute(value);
}

function hasDotDot(value) {
  return String(value).split(/[\\/]/).includes('..');
}

function requireAbsolute(value, code) {
  if (typeof value !== 'string' || value.length === 0 || value.includes('\0') ||
      !isAbs(value) || hasDotDot(value)) {
    throw failure(code);
  }
  return value;
}

function requireRegularFile(filePath, ioFs, code) {
  const resolved = requireAbsolute(filePath, code);
  let stat;
  try { stat = ioFs.lstatSync(resolved); } catch (_) { throw failure(code); }
  if (stat.isSymbolicLink() || !stat.isFile()) throw failure(code);
  return resolved;
}

function requireDirectory(dirPath, ioFs, code) {
  const resolved = requireAbsolute(dirPath, code);
  let stat;
  try { stat = ioFs.lstatSync(resolved); } catch (_) { throw failure(code); }
  if (stat.isSymbolicLink() || !stat.isDirectory()) throw failure(code);
  return resolved;
}

function starlarkString(value) {
  return JSON.stringify(value);
}

function prefixRule(pattern, justification) {
  const items = pattern.map(item => `        ${starlarkString(item)},`).join('\n');
  return [
    'prefix_rule(',
    '    pattern = [',
    items,
    '    ],',
    '    decision = "allow",',
    `    justification = ${starlarkString(justification)},`,
    ')',
    '',
  ].join('\n');
}

function invocationAliases(absPath) {
  const aliases = [];
  function add(value) {
    if (typeof value === 'string' && value.length > 0 && !aliases.includes(value)) aliases.push(value);
  }
  add(absPath);
  const posix = String(absPath).replace(/\\/g, '/');
  const winDrive = /^([A-Za-z]):(?:\/|\\)(.*)$/.exec(absPath);
  if (winDrive) {
    add(`${winDrive[1].toUpperCase()}:\\${winDrive[2].replace(/\//g, '\\')}`);
    add(`/mnt/${winDrive[1].toLowerCase()}/${winDrive[2].replace(/\\/g, '/')}`);
  }
  const mnt = /^\/mnt\/([a-z])\/(.+)$/.exec(posix);
  if (mnt) {
    add(`${mnt[1].toUpperCase()}:\\${mnt[2].replace(/\//g, '\\')}`);
    add(`/mnt/${mnt[1]}/${mnt[2]}`);
  }
  return aliases;
}

function invocationPairs(nodePath, scriptPath) {
  const pairs = [];
  const seen = new Set();
  for (const node of invocationAliases(nodePath)) {
    for (const script of invocationAliases(scriptPath)) {
      const key = node + '\0' + script;
      if (seen.has(key)) continue;
      seen.add(key);
      pairs.push([node, script]);
    }
  }
  return pairs;
}

function historyPattern(nodePath, scriptPath, name) {
  return [nodePath, scriptPath, 'history', '--connection', name, '--drain', '--json'];
}

function sayPattern(nodePath, scriptPath, name) {
  return [nodePath, scriptPath, 'say', '--connection', name, '--file'];
}

function generatePolicy(options) {
  const name = options.connection;
  const mode = options.mode;
  const nodePath = options.nodePath;
  const scriptPath = options.scriptPath;
  if (!validConnectionName(name)) throw failure('invalid-connection');
  if (!MODES.includes(mode)) throw failure('invalid-mode');
  if (typeof nodePath !== 'string' || nodePath.includes('\0') || !isAbs(nodePath) ||
      hasDotDot(nodePath)) {
    throw failure('invalid-node');
  }
  if (typeof scriptPath !== 'string' || scriptPath.includes('\0') || !isAbs(scriptPath) ||
      hasDotDot(scriptPath) || path.basename(scriptPath) !== 'interlock.js' &&
      path.win32.basename(scriptPath) !== 'interlock.js') {
    throw failure('invalid-script');
  }

  const pairs = invocationPairs(nodePath, scriptPath);
  const history = pairs.map(([node, script]) => prefixRule(
    historyPattern(node, script, name),
    'Interlock receive: canonical history --drain --json for this named connection. Drain acknowledges addressed rows and advances that connection cursor.',
  )).join('');
  const say = mode === 'participate' ? pairs.map(([node, script]) => prefixRule(
    sayPattern(node, script, name),
    'Interlock participate: canonical say --file for this named connection. Codex may send any readable file through this seat without per-message Auto-review. No payload inspection, classification, redaction, or restriction.',
  )).join('') : '';
  const body = [
    `# ${MARKER}`,
    '# Generated by interlock codex-policy. Do not edit.',
    '# One Interlock-owned file. Installing for a connection replaces any previous Interlock policy.',
    `# connection=${name}`,
    `# mode=${mode}`,
    `# node=${nodePath}`,
    `# script=${scriptPath}`,
    '',
    history,
    say,
  ].join('\n').replace(/\n+$/, '\n');
  const digest = crypto.createHash('sha256').update(body, 'utf8').digest('hex');
  return body.replace(`# ${MARKER}\n`, `# ${MARKER}\n# sha256=${digest}\n`);
}

function parseOwned(text) {
  if (typeof text !== 'string' || !text.startsWith(`# ${MARKER}\n`)) return null;
  const connection = text.match(/^# connection=([A-Za-z0-9-]+)$/m);
  const mode = text.match(/^# mode=(receive|participate)$/m);
  const node = text.match(/^# node=(.+)$/m);
  const script = text.match(/^# script=(.+)$/m);
  const digest = text.match(/^# sha256=([0-9a-f]{64})$/m);
  if (!connection || !mode || !node || !script || !digest) return null;
  return {
    connection: connection[1],
    mode: mode[1],
    nodePath: node[1],
    scriptPath: script[1],
    sha256: digest[1],
  };
}

function isOwnedExact(text, options) {
  return text === generatePolicy(options);
}

function policyPaths(rulesDir) {
  return { owned: path.join(rulesDir, OWNED_NAME) };
}

function uniqueTmpPath(rulesDir) {
  return path.join(rulesDir,
    `${OWNED_NAME}.${process.pid}.${crypto.randomBytes(8).toString('hex')}.tmp`);
}

function explicitEnvHome(options) {
  const envHome = options.env && options.env.CODEX_HOME;
  if (typeof envHome !== 'string' || envHome.length === 0) return null;
  if (!isAbs(envHome) || hasDotDot(envHome)) throw failure('invalid-codex-home');
  return envHome;
}

function fallbackHomes(options) {
  const homes = [];
  const homedir = options.homedir || os.homedir();
  if (typeof homedir === 'string' && homedir.length > 0) {
    homes.push(path.join(homedir, '.codex'));
  }
  const userProfile = options.env && options.env.USERPROFILE;
  if (typeof userProfile === 'string' && userProfile.length > 0) {
    const winHome = `${userProfile.replace(/[\\/]$/, '')}\\.codex`;
    homes.push(winHome);
    for (const alias of invocationAliases(winHome)) homes.push(alias);
  }
  return [...new Set(homes)];
}

function ensureRulesDir(home, ioFs) {
  if (!ioFs.existsSync(home)) ioFs.mkdirSync(home, { recursive: true, mode: 0o700 });
  const root = requireDirectory(home, ioFs, 'invalid-codex-home');
  const rules = path.join(root, 'rules');
  if (!ioFs.existsSync(rules)) ioFs.mkdirSync(rules, { recursive: true, mode: 0o700 });
  return requireDirectory(rules, ioFs, 'invalid-codex-home');
}

function resolveRulesDir(options, ioFs) {
  if (options.codexHome) return ensureRulesDir(options.codexHome, ioFs);
  const envHome = explicitEnvHome(options);
  if (envHome) return ensureRulesDir(envHome, ioFs);
  const existing = [];
  for (const home of fallbackHomes(options)) {
    try { existing.push(requireDirectory(home, ioFs, 'invalid-codex-home')); } catch (_) { /* skip */ }
  }
  const unique = [...new Set(existing)];
  if (unique.length > 1) throw failure('ambiguous-codex-home');
  const home = unique[0] || (options.homedir || os.homedir()
    ? path.join(options.homedir || os.homedir(), '.codex')
    : null);
  if (!home) throw failure('ambiguous-codex-home');
  return ensureRulesDir(home, ioFs);
}

function resolvedCodexHome(rulesDir) {
  return path.basename(rulesDir) === 'rules' ? path.dirname(rulesDir) : rulesDir;
}

function shellQuote(value) {
  if (typeof value !== 'string') return '';
  if (/^[A-Za-z0-9:._\\/-]+$/.test(value)) return value;
  return `"${value.replace(/"/g, '\\"')}"`;
}

function policyHandoff(action, connection, codexHome) {
  return `interlock codex-policy ${action} --connection ${connection} --codex-home ${shellQuote(codexHome)}`;
}

function resolveCodexNode(options, ioFs) {
  if (options.nodePath) return requireRegularFile(options.nodePath, ioFs, 'invalid-node');
  const candidates = [];
  const localAppData = options.env && options.env.LOCALAPPDATA;
  if (typeof localAppData === 'string' && localAppData.length > 0) {
    candidates.push(path.join(localAppData, 'OpenAI', 'Codex', 'bin',
      options.platform === 'win32' ? 'node.exe' : 'node'));
  }
  const execPath = options.execPath;
  if (typeof execPath === 'string' && /openai[\\/]codex/i.test(execPath)) {
    candidates.push(execPath);
  }
  const existing = [];
  for (const candidate of candidates) {
    try { existing.push(requireRegularFile(candidate, ioFs, 'invalid-node')); } catch (_) { /* skip */ }
  }
  const unique = [...new Set(existing)];
  if (unique.length !== 1) throw failure('ambiguous-codex-node');
  return unique[0];
}

function resolveInterlockScript(options, ioFs) {
  const scriptPath = options.scriptPath || path.resolve(__dirname, '..', 'bin', 'interlock.js');
  const resolved = requireRegularFile(scriptPath, ioFs, 'invalid-script');
  if (path.basename(resolved) !== 'interlock.js' &&
      path.win32.basename(resolved) !== 'interlock.js') {
    throw failure('invalid-script');
  }
  return resolved;
}

function versionedCheckerDir(filePath) {
  const posix = String(filePath).replace(/\\/g, '/');
  const wsl = /\/bin\/wsl\/([0-9a-f]{8,})(?:\/|$)/i.exec(posix);
  if (wsl) return { kind: 'wsl', id: wsl[1] };
  const win = /\/OpenAI\/Codex\/bin\/([0-9a-f]{8,})(?:\/|$)/i.exec(posix);
  if (win) return { kind: 'win', id: win[1] };
  return null;
}

function checkerInDir(dir, ioFs) {
  for (const name of ['codex', 'codex.exe']) {
    const candidate = path.join(dir, name);
    try { return requireRegularFile(candidate, ioFs, 'execpolicy-unavailable'); } catch (_) { /* next */ }
  }
  return null;
}

function scanVersionedCheckers(root, ioFs) {
  const found = [];
  if (!root || !ioFs.existsSync(root)) return found;
  let entries;
  try { entries = ioFs.readdirSync(root, { withFileTypes: true }); } catch (_) { return found; }
  for (const entry of entries) {
    if (!entry.isDirectory() || !/^[0-9a-f]{8,}$/i.test(entry.name)) continue;
    const checker = checkerInDir(path.join(root, entry.name), ioFs);
    if (checker) found.push(checker);
  }
  return found;
}

function resolveCodexChecker(options, ioFsIn) {
  const ioFs = ioFsIn || options.fs || fs;
  if (options.checkerPath) return requireRegularFile(options.checkerPath, ioFs, 'execpolicy-unavailable');
  const selected = [];
  const execPath = options.execPath;
  if (typeof execPath === 'string' && execPath.length > 0) {
    const versioned = versionedCheckerDir(execPath);
    if (versioned) {
      const checker = checkerInDir(path.dirname(execPath), ioFs);
      if (checker) selected.push(checker);
    }
  }
  const homes = [];
  try { homes.push(resolvedCodexHome(resolveRulesDir(options, ioFs))); } catch (_) { /* no home yet */ }
  for (const home of homes) {
    selected.push(...scanVersionedCheckers(path.join(home, 'bin', 'wsl'), ioFs));
    selected.push(...scanVersionedCheckers(path.join(home, 'bin'), ioFs));
  }
  const localAppData = options.env && options.env.LOCALAPPDATA;
  if (typeof localAppData === 'string' && localAppData.length > 0) {
    selected.push(...scanVersionedCheckers(path.join(localAppData, 'OpenAI', 'Codex', 'bin'), ioFs));
  }
  const unique = [...new Set(selected)];
  if (unique.length === 1) return unique[0];
  throw failure(unique.length > 1 ? 'ambiguous-codex-checker' : 'execpolicy-unavailable');
}

function readOwned(rulesDir, ioFs) {
  const owned = policyPaths(rulesDir).owned;
  if (!ioFs.existsSync(owned)) return null;
  const stat = ioFs.lstatSync(owned);
  if (stat.isSymbolicLink() || !stat.isFile()) throw failure('owned-file-unsafe');
  return ioFs.readFileSync(owned, 'utf8');
}

function pidAlive(pid) {
  if (!Number.isSafeInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    if (error && error.code === 'ESRCH') return false;
    return true;
  }
}

function withOwnedLock(rulesDir, ioFs, fn) {
  const lockPath = path.join(rulesDir, `${OWNED_NAME}.lock`);
  function take() {
    const fd = ioFs.openSync(lockPath, 'wx');
    const payload = `${JSON.stringify({
      pid: process.pid,
      started: Date.now(),
      nonce: crypto.randomBytes(8).toString('hex'),
    })}\n`;
    ioFs.writeFileSync(fd, payload);
    return fd;
  }
  let fd;
  try {
    fd = take();
  } catch (_) {
    let stale = false;
    try {
      const parsed = JSON.parse(ioFs.readFileSync(lockPath, 'utf8'));
      stale = !pidAlive(parsed && parsed.pid);
    } catch (_) {
      stale = false;
    }
    if (!stale) throw failure('owned-file-unsafe');
    try { ioFs.unlinkSync(lockPath); } catch (_) { throw failure('owned-file-unsafe'); }
    fd = take();
  }
  try { return fn(); } finally {
    try { ioFs.closeSync(fd); } catch (_) { /* ignore */ }
    try { ioFs.unlinkSync(lockPath); } catch (_) { /* ignore */ }
  }
}

function writeTmp(rulesDir, contents, ioFs) {
  const tmpPath = uniqueTmpPath(rulesDir);
  ioFs.writeFileSync(tmpPath, contents, { encoding: 'utf8', mode: 0o600, flag: 'wx' });
  const fd = ioFs.openSync(tmpPath, 'r+');
  try { ioFs.fsyncSync(fd); } finally { ioFs.closeSync(fd); }
  return tmpPath;
}

function decideExecpolicy(result) {
  if (!result || typeof result !== 'object') return 'unsupported';
  if (result.decision === 'allow') return 'allow';
  if (result.decision === 'deny' || result.decision === 'ask') return result.decision;
  if (Array.isArray(result.matchedRules) && result.matchedRules.length === 0) return 'deny';
  return 'unsupported';
}

function expectedChecks(spec) {
  const { nodePath, scriptPath, connection, mode } = spec;
  const pairs = invocationPairs(nodePath, scriptPath);
  const positives = [];
  for (const [node, script] of pairs) {
    positives.push(historyPattern(node, script, connection));
    if (mode === 'participate') {
      positives.push(sayPattern(node, script, connection).concat(['message.md']));
    }
  }
  const [node, script] = pairs[0];
  const negatives = [
    ['node', script, 'history', '--connection', connection, '--drain', '--json'],
    [node, 'bin/interlock.js', 'history', '--connection', connection, '--drain', '--json'],
    [node, script, 'history', '--connection', 'OtherName', '--drain', '--json'],
    [node, script, 'leave', '--connection', connection],
    [node, script, 'say', '--connection', connection, '--stdin'],
    [node, script, 'join'],
    historyPattern(node, script, connection).slice().reverse(),
  ];
  if (mode === 'receive') {
    negatives.push(sayPattern(node, script, connection).concat(['message.md']));
  }
  return { positives, negatives };
}

function decideChecker(options, rulesPath, command) {
  if (typeof options.checkExecpolicy === 'function') {
    return decideExecpolicy(options.checkExecpolicy(rulesPath, command));
  }
  const ioFs = options.fs || fs;
  const checkerPath = resolveCodexChecker(options, ioFs);
  const spawnSync = options.spawnSync || require('node:child_process').spawnSync;
  const result = spawnSync(checkerPath, ['execpolicy', 'check', '--rules', rulesPath, '--', ...command], {
    encoding: 'utf8',
    timeout: 20_000,
  });
  if (result.error) throw failure('execpolicy-unavailable');
  if (result.signal) throw failure('execpolicy-unavailable');
  if (result.status !== 0) throw failure('execpolicy-rejected');
  const text = String(result.stdout || '').trim();
  if (!text.startsWith('{')) throw failure('execpolicy-unavailable');
  let parsed;
  try { parsed = JSON.parse(text); } catch (_) { throw failure('execpolicy-unavailable'); }
  return decideExecpolicy(parsed);
}

function installPolicy(options) {
  const ioFs = options.fs || fs;
  const connection = options.connection;
  const mode = options.mode;
  if (!validConnectionName(connection)) throw failure('invalid-connection');
  if (!MODES.includes(mode)) throw failure('invalid-mode');
  const rulesDir = resolveRulesDir(options, ioFs);
  const nodePath = resolveCodexNode(options, ioFs);
  const scriptPath = resolveInterlockScript(options, ioFs);
  const spec = { connection, mode, nodePath, scriptPath };
  const contents = generatePolicy(spec);
  return withOwnedLock(rulesDir, ioFs, () => {
    const existing = readOwned(rulesDir, ioFs);
    let replaced = null;
    if (existing !== null) {
      const parsed = parseOwned(existing);
      if (!parsed || !isOwnedExact(existing, parsed)) throw failure('owned-file-modified');
      replaced = parsed.connection;
    }
    const tmpPath = writeTmp(rulesDir, contents, ioFs);
    try {
      const checks = expectedChecks(spec);
      const checkerOptions = Object.assign({}, options, { nodePath });
      for (const command of checks.positives) {
        if (decideChecker(checkerOptions, tmpPath, command) !== 'allow') {
          throw failure('execpolicy-rejected', command.join(' '));
        }
      }
      for (const command of checks.negatives) {
        const decision = decideChecker(checkerOptions, tmpPath, command);
        if (decision === 'allow') throw failure('execpolicy-too-broad');
        if (decision === 'unsupported') throw failure('execpolicy-unavailable');
      }
      ioFs.renameSync(tmpPath, policyPaths(rulesDir).owned);
    } catch (error) {
      try { ioFs.unlinkSync(tmpPath); } catch (_) { /* leftover tmp is inactive */ }
      throw error;
    }
    const codexHome = resolvedCodexHome(rulesDir);
    return Object.freeze({
      path: policyPaths(rulesDir).owned,
      mode,
      connection,
      nodePath,
      scriptPath,
      codexHome,
      historyArgv: historyPattern(nodePath, scriptPath, connection),
      sayArgv: mode === 'participate' ? sayPattern(nodePath, scriptPath, connection) : null,
      restartRequired: true,
      active: 'unknown',
      replacedConnection: replaced && replaced !== connection ? replaced : null,
      checkCommand: policyHandoff('check', connection, codexHome),
      removeCommand: policyHandoff('remove', connection, codexHome),
    });
  });
}

function checkPolicy(options) {
  const ioFs = options.fs || fs;
  const connection = options.connection;
  if (!validConnectionName(connection)) throw failure('invalid-connection');
  const rulesDir = resolveRulesDir(options, ioFs);
  const existing = readOwned(rulesDir, ioFs);
  if (existing === null) throw failure('not-installed');
  const parsed = parseOwned(existing);
  if (!parsed || !isOwnedExact(existing, parsed)) throw failure('owned-file-modified');
  if (parsed.connection !== connection) throw failure('connection-mismatch');
  const checks = expectedChecks(parsed);
  const checkerOptions = Object.assign({}, options, { nodePath: parsed.nodePath });
  const owned = policyPaths(rulesDir).owned;
  for (const command of checks.positives) {
    if (decideChecker(checkerOptions, owned, command) !== 'allow') {
      throw failure('execpolicy-rejected');
    }
  }
  for (const command of checks.negatives) {
    const decision = decideChecker(checkerOptions, owned, command);
    if (decision === 'allow') throw failure('execpolicy-too-broad');
    if (decision === 'unsupported') throw failure('execpolicy-unavailable');
  }
  const codexHome = resolvedCodexHome(rulesDir);
  return Object.freeze({
    path: owned,
    mode: parsed.mode,
    connection: parsed.connection,
    nodePath: parsed.nodePath,
    scriptPath: parsed.scriptPath,
    codexHome,
    restartRequired: true,
    active: 'unknown',
    syntaxOnly: true,
    checkCommand: policyHandoff('check', connection, codexHome),
    removeCommand: policyHandoff('remove', connection, codexHome),
  });
}

function removePolicy(options) {
  const ioFs = options.fs || fs;
  const connection = options.connection;
  if (!validConnectionName(connection)) throw failure('invalid-connection');
  const rulesDir = resolveRulesDir(options, ioFs);
  return withOwnedLock(rulesDir, ioFs, () => {
    const existing = readOwned(rulesDir, ioFs);
    if (existing === null) throw failure('not-installed');
    const parsed = parseOwned(existing);
    if (!parsed || !isOwnedExact(existing, parsed)) throw failure('owned-file-modified');
    if (parsed.connection !== connection) throw failure('connection-mismatch');
    ioFs.unlinkSync(policyPaths(rulesDir).owned);
    const codexHome = resolvedCodexHome(rulesDir);
    return Object.freeze({
      removed: policyPaths(rulesDir).owned,
      connection,
      codexHome,
    });
  });
}

module.exports = {
  OWNED_NAME,
  MARKER,
  generatePolicy,
  parseOwned,
  expectedChecks,
  invocationAliases,
  installPolicy,
  checkPolicy,
  removePolicy,
  resolveCodexChecker,
  historyPattern,
  sayPattern,
};
