'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const OWNED_NAME = 'interlock-codex-policy.rules';
const TMP_NAME = 'interlock-codex-policy.rules.tmp';
const MARKER = 'INTERLOCK-CODEX-POLICY 1';
const MODES = Object.freeze(['receive', 'participate']);
const AI_NAME = /^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/;

function failure(code, detail) {
  const error = new Error(detail ? 'codex_policy: ' + code + ': ' + detail : 'codex_policy: ' + code);
  error.code = code;
  return error;
}

function validConnectionName(value) {
  return typeof value === 'string' && value.length >= 2 && value.length <= 24 &&
    AI_NAME.test(value) && value.toLowerCase() !== 'all';
}

function requireAbsolute(value, code) {
  if (typeof value !== 'string' || value.length === 0 || value.includes('\0') ||
      !path.isAbsolute(value)) {
    throw failure(code);
  }
  const resolved = path.resolve(value);
  if (resolved !== path.normalize(resolved)) throw failure(code);
  return resolved;
}

function requireRegularFile(filePath, ioFs, code) {
  const resolved = requireAbsolute(filePath, code);
  let stat;
  try { stat = ioFs.lstatSync(resolved); } catch (_) { throw failure(code); }
  if (stat.isSymbolicLink() || !stat.isFile()) throw failure(code);
  return resolved;
}

function requireDirectory(dirPath, ioFs, code) {
  const resolved = requireAbsolute(dirPath, code);
  let stat;
  try { stat = ioFs.lstatSync(resolved); } catch (_) { throw failure(code); }
  if (stat.isSymbolicLink() || !stat.isDirectory()) throw failure(code);
  return resolved;
}

function starlarkString(value) {
  return JSON.stringify(value);
}

function prefixRule(pattern, justification) {
  const items = pattern.map(item => `        ${starlarkString(item)},`).join('\n');
  return [
    'prefix_rule(',
    '    pattern = [',
    items,
    '    ],',
    '    decision = "allow",',
    `    justification = ${starlarkString(justification)},`,
    ')',
    '',
  ].join('\n');
}

function historyPattern(nodePath, scriptPath, name) {
  return [nodePath, scriptPath, 'history', '--connection', name, '--drain', '--json'];
}

function sayPattern(nodePath, scriptPath, name) {
  return [nodePath, scriptPath, 'say', '--connection', name, '--file'];
}

function generatePolicy(options) {
  const name = options.connection;
  const mode = options.mode;
  const nodePath = options.nodePath;
  const scriptPath = options.scriptPath;
  if (!validConnectionName(name)) throw failure('invalid-connection');
  if (!MODES.includes(mode)) throw failure('invalid-mode');
  if (typeof nodePath !== 'string' || !path.isAbsolute(nodePath) || nodePath.includes('\0')) {
    throw failure('invalid-node');
  }
  if (typeof scriptPath !== 'string' || !path.isAbsolute(scriptPath) ||
      scriptPath.includes('\0') || path.basename(scriptPath) !== 'interlock.js') {
    throw failure('invalid-script');
  }
  if (scriptPath !== path.normalize(scriptPath) || nodePath !== path.normalize(nodePath)) {
    throw failure('invalid-path');
  }
  if (scriptPath.includes('..') || nodePath.includes('..')) throw failure('invalid-path');

  const history = prefixRule(
    historyPattern(nodePath, scriptPath, name),
    'Interlock receive: canonical history --drain --json for this named connection. Drain acknowledges addressed rows and advances that connection cursor.',
  );
  const say = mode === 'participate' ? prefixRule(
    sayPattern(nodePath, scriptPath, name),
    'Interlock participate: canonical say --file for this named connection. Codex may send any readable file through this seat without per-message Auto-review. No payload inspection, classification, redaction, or restriction.',
  ) : '';
  const body = [
    `# ${MARKER}`,
    '# Generated by interlock codex-policy. Do not edit.',
    `# connection=${name}`,
    `# mode=${mode}`,
    `# node=${nodePath}`,
    `# script=${scriptPath}`,
    '',
    history,
    say,
  ].join('\n').replace(/\n+$/, '\n');
  const digest = crypto.createHash('sha256').update(body, 'utf8').digest('hex');
  return body.replace(`# ${MARKER}\n`, `# ${MARKER}\n# sha256=${digest}\n`);
}

function parseOwned(text) {
  if (typeof text !== 'string' || !text.startsWith(`# ${MARKER}\n`)) return null;
  const connection = text.match(/^# connection=([A-Za-z0-9-]+)$/m);
  const mode = text.match(/^# mode=(receive|participate)$/m);
  const node = text.match(/^# node=(.+)$/m);
  const script = text.match(/^# script=(.+)$/m);
  const digest = text.match(/^# sha256=([0-9a-f]{64})$/m);
  if (!connection || !mode || !node || !script || !digest) return null;
  return {
    connection: connection[1],
    mode: mode[1],
    nodePath: node[1],
    scriptPath: script[1],
    sha256: digest[1],
  };
}

function isOwnedExact(text, options) {
  return text === generatePolicy(options);
}

function policyPaths(rulesDir) {
  return {
    owned: path.join(rulesDir, OWNED_NAME),
    tmp: path.join(rulesDir, TMP_NAME),
  };
}

function resolveRulesDir(options, ioFs) {
  if (options.codexHome) {
    const home = requireDirectory(options.codexHome, ioFs, 'invalid-codex-home');
    const rules = path.join(home, 'rules');
    if (!ioFs.existsSync(rules)) ioFs.mkdirSync(rules, { recursive: true, mode: 0o700 });
    return requireDirectory(rules, ioFs, 'invalid-codex-home');
  }
  const homes = [];
  const envHome = options.env && options.env.CODEX_HOME;
  if (typeof envHome === 'string' && envHome.length > 0) homes.push(envHome);
  if (typeof options.homedir === 'string' && options.homedir.length > 0) {
    homes.push(path.join(options.homedir, '.codex'));
  }
  const existing = [];
  for (const home of homes) {
    try {
      existing.push(requireDirectory(home, ioFs, 'invalid-codex-home'));
    } catch (_) { /* candidate absent */ }
  }
  const unique = [...new Set(existing)];
  if (unique.length !== 1) throw failure('ambiguous-codex-home');
  const rules = path.join(unique[0], 'rules');
  if (!ioFs.existsSync(rules)) ioFs.mkdirSync(rules, { recursive: true, mode: 0o700 });
  return requireDirectory(rules, ioFs, 'invalid-codex-home');
}

function resolveCodexNode(options, ioFs) {
  if (options.nodePath) return requireRegularFile(options.nodePath, ioFs, 'invalid-node');
  const candidates = [];
  const localAppData = options.env && options.env.LOCALAPPDATA;
  if (typeof localAppData === 'string' && localAppData.length > 0) {
    candidates.push(path.join(localAppData, 'OpenAI', 'Codex', 'bin',
      options.platform === 'win32' ? 'node.exe' : 'node'));
  }
  const execPath = options.execPath;
  if (typeof execPath === 'string' && /openai[\\/]codex/i.test(execPath)) {
    candidates.push(execPath);
  }
  const existing = [];
  for (const candidate of candidates) {
    try { existing.push(requireRegularFile(candidate, ioFs, 'invalid-node')); } catch (_) { /* skip */ }
  }
  const unique = [...new Set(existing)];
  if (unique.length !== 1) throw failure('ambiguous-codex-node');
  return unique[0];
}

function resolveInterlockScript(options, ioFs) {
  const scriptPath = options.scriptPath || path.resolve(__dirname, '..', 'bin', 'interlock.js');
  const resolved = requireRegularFile(scriptPath, ioFs, 'invalid-script');
  if (path.basename(resolved) !== 'interlock.js') throw failure('invalid-script');
  return resolved;
}

function readOwned(rulesDir, ioFs) {
  const owned = policyPaths(rulesDir).owned;
  if (!ioFs.existsSync(owned)) return null;
  const stat = ioFs.lstatSync(owned);
  if (stat.isSymbolicLink() || !stat.isFile()) throw failure('owned-file-unsafe');
  return ioFs.readFileSync(owned, 'utf8');
}

function atomicWrite(rulesDir, contents, ioFs) {
  const paths = policyPaths(rulesDir);
  ioFs.writeFileSync(paths.tmp, contents, { encoding: 'utf8', mode: 0o600, flag: 'w' });
  const fd = ioFs.openSync(paths.tmp, 'r+');
  try { ioFs.fsyncSync(fd); } finally { ioFs.closeSync(fd); }
  ioFs.renameSync(paths.tmp, paths.owned);
}

function removeTmp(rulesDir, ioFs) {
  const tmp = policyPaths(rulesDir).tmp;
  try { ioFs.unlinkSync(tmp); } catch (_) { /* leftover tmp is inactive */ }
}

function decideExecpolicy(result) {
  if (!result || typeof result !== 'object') return 'unsupported';
  if (result.decision === 'allow') return 'allow';
  if (result.decision === 'deny' || result.decision === 'ask') return result.decision;
  if (Array.isArray(result.matchedRules) && result.matchedRules.length === 0) return 'deny';
  return 'unsupported';
}

function expectedChecks(spec) {
  const { nodePath, scriptPath, connection, mode } = spec;
  const positives = [
    historyPattern(nodePath, scriptPath, connection),
  ];
  if (mode === 'participate') {
    positives.push(sayPattern(nodePath, scriptPath, connection).concat(['message.md']));
  }
  const negatives = [
    ['node', scriptPath, 'history', '--connection', connection, '--drain', '--json'],
    [nodePath, 'bin/interlock.js', 'history', '--connection', connection, '--drain', '--json'],
    [nodePath, scriptPath, 'history', '--connection', 'OtherName', '--drain', '--json'],
    [nodePath, scriptPath, 'leave', '--connection', connection],
    [nodePath, scriptPath, 'say', '--connection', connection, '--stdin'],
    [nodePath, scriptPath, 'join'],
    historyPattern(nodePath, scriptPath, connection).slice().reverse(),
  ];
  if (mode === 'receive') {
    negatives.push(sayPattern(nodePath, scriptPath, connection).concat(['message.md']));
  }
  return { positives, negatives };
}

function installPolicy(options) {
  const ioFs = options.fs || fs;
  const connection = options.connection;
  const mode = options.mode;
  if (!validConnectionName(connection)) throw failure('invalid-connection');
  if (!MODES.includes(mode)) throw failure('invalid-mode');
  const rulesDir = resolveRulesDir(options, ioFs);
  const nodePath = resolveCodexNode(options, ioFs);
  const scriptPath = resolveInterlockScript(options, ioFs);
  const spec = { connection, mode, nodePath, scriptPath };
  const contents = generatePolicy(spec);
  const existing = readOwned(rulesDir, ioFs);
  if (existing !== null) {
    const parsed = parseOwned(existing);
    if (!parsed || !isOwnedExact(existing, parsed)) throw failure('owned-file-modified');
  }
  removeTmp(rulesDir, ioFs);
  const tmpPath = policyPaths(rulesDir).tmp;
  ioFs.writeFileSync(tmpPath, contents, { encoding: 'utf8', mode: 0o600, flag: 'w' });
  const fd = ioFs.openSync(tmpPath, 'r+');
  try { ioFs.fsyncSync(fd); } finally { ioFs.closeSync(fd); }
  const checks = expectedChecks(spec);
  const checker = options.checkExecpolicy;
  if (typeof checker !== 'function') throw failure('execpolicy-unavailable');
  for (const command of checks.positives) {
    const decision = decideExecpolicy(checker(tmpPath, command));
    if (decision !== 'allow') {
      removeTmp(rulesDir, ioFs);
      throw failure('execpolicy-rejected', command.join(' '));
    }
  }
  for (const command of checks.negatives) {
    const decision = decideExecpolicy(checker(tmpPath, command));
    if (decision === 'allow' || decision === 'unsupported') {
      removeTmp(rulesDir, ioFs);
      throw failure(decision === 'allow' ? 'execpolicy-too-broad' : 'execpolicy-unavailable');
    }
  }
  ioFs.renameSync(tmpPath, policyPaths(rulesDir).owned);
  return Object.freeze({
    path: policyPaths(rulesDir).owned,
    mode,
    connection,
    nodePath,
    scriptPath,
    historyArgv: historyPattern(nodePath, scriptPath, connection),
    sayArgv: mode === 'participate' ? sayPattern(nodePath, scriptPath, connection) : null,
    restartRequired: true,
    active: false,
    removeCommand: `interlock codex-policy remove --connection ${connection}`,
  });
}

function checkPolicy(options) {
  const ioFs = options.fs || fs;
  const connection = options.connection;
  if (!validConnectionName(connection)) throw failure('invalid-connection');
  const rulesDir = resolveRulesDir(options, ioFs);
  const existing = readOwned(rulesDir, ioFs);
  if (existing === null) throw failure('not-installed');
  const parsed = parseOwned(existing);
  if (!parsed || !isOwnedExact(existing, parsed)) throw failure('owned-file-modified');
  if (parsed.connection !== connection) throw failure('connection-mismatch');
  const checker = options.checkExecpolicy;
  if (typeof checker !== 'function') throw failure('execpolicy-unavailable');
  const checks = expectedChecks(parsed);
  for (const command of checks.positives) {
    if (decideExecpolicy(checker(policyPaths(rulesDir).owned, command)) !== 'allow') {
      throw failure('execpolicy-rejected');
    }
  }
  for (const command of checks.negatives) {
    const decision = decideExecpolicy(checker(policyPaths(rulesDir).owned, command));
    if (decision === 'allow') throw failure('execpolicy-too-broad');
    if (decision === 'unsupported') throw failure('execpolicy-unavailable');
  }
  return Object.freeze({
    path: policyPaths(rulesDir).owned,
    mode: parsed.mode,
    connection: parsed.connection,
    nodePath: parsed.nodePath,
    scriptPath: parsed.scriptPath,
    restartRequired: true,
    active: false,
  });
}

function removePolicy(options) {
  const ioFs = options.fs || fs;
  const connection = options.connection;
  if (!validConnectionName(connection)) throw failure('invalid-connection');
  const rulesDir = resolveRulesDir(options, ioFs);
  const existing = readOwned(rulesDir, ioFs);
  if (existing === null) throw failure('not-installed');
  const parsed = parseOwned(existing);
  if (!parsed || !isOwnedExact(existing, parsed)) throw failure('owned-file-modified');
  if (parsed.connection !== connection) throw failure('connection-mismatch');
  const defaultRules = path.join(rulesDir, 'default.rules');
  if (ioFs.existsSync(defaultRules)) {
    const defaultStat = ioFs.lstatSync(defaultRules);
    if (defaultStat.isSymbolicLink()) throw failure('owned-file-unsafe');
  }
  ioFs.unlinkSync(policyPaths(rulesDir).owned);
  removeTmp(rulesDir, ioFs);
  return Object.freeze({ removed: policyPaths(rulesDir).owned, connection });
}

module.exports = {
  OWNED_NAME,
  MARKER,
  generatePolicy,
  parseOwned,
  expectedChecks,
  installPolicy,
  checkPolicy,
  removePolicy,
  historyPattern,
  sayPattern,
};
